# Indexação, Slicing e Iteração

Array uni-dimensional podem ser idenxados, repartidos e iterados muito similarmente a lista e outras sequências do Python.

In [1]:
import numpy as np

a = np.arange(10)**2

print(a)

print(a[4])

print(a[5:])

print(a[::2]) # de 2 em dois

print(a[::-1]) # invertendo

[ 0  1  4  9 16 25 36 49 64 81]
16
[25 36 49 64 81]
[ 0  4 16 36 64]
[81 64 49 36 25 16  9  4  1  0]


Array multidimensional tem um indice por eixo.

In [2]:
a = (np.arange(16)**2).reshape((4, 4))

print(a)

# elemento da linha 0 e coluna 1
print(a[0, 1])

print(a[:3, 0]) # elementos da linha 0 a 2 da coluna 0

print(a[:, 0]) # todos elementos da coluna 0

print(a[-1]) # equivalente a a[-1, :]

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
1
[ 0 16 64]
[  0  16  64 144]
[144 169 196 225]


In [3]:
for linha in a:
    print(linha)

[0 1 4 9]
[16 25 36 49]
[ 64  81 100 121]
[144 169 196 225]


## Manipulação do Shape

In [4]:
a = (np.arange(16)**2).reshape((4, 4))

print(a)

# flattened array
print(a.ravel())

# retorna array com novo formato
print(a.reshape(8,2))

# transposta
print(a.T)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
[[  0   1]
 [  4   9]
 [ 16  25]
 [ 36  49]
 [ 64  81]
 [100 121]
 [144 169]
 [196 225]]
[[  0  16  64 144]
 [  1  25  81 169]
 [  4  36 100 196]
 [  9  49 121 225]]


## Truques de Indexação

NumPy oferece mais opções de indexação do que Python. Além da indexação por inteiros e slices, como vimos anteriormente, arrays podem ser indexados por outros arrays de inteiros e booleanos.

In [5]:
a = np.arange(12)**2                      
indices = np.array([1, 1, 6, 3, 5])

print(a[indices])

bidim_indices = np.array([[1, 6], [3, 5]])

print(a[bidim_indices])

[ 1  1 36  9 25]
[[ 1 36]
 [ 9 25]]


Quando estamos indexando um array multimensional, um único array de indices refere-se a primeira dimensão de **a**.

In [6]:
a = (np.arange(21)**2).reshape((7, 3))

print(a)

bidim_indices = np.array([[1, 0], [2, 6]])

a[bidim_indices] 

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]
 [144 169 196]
 [225 256 289]
 [324 361 400]]


array([[[  9,  16,  25],
        [  0,   1,   4]],

       [[ 36,  49,  64],
        [324, 361, 400]]], dtype=int32)

In [7]:
# tem de ter o mesmo tamanho
id_linhas = np.array([0, 1, 5])
id_colunas = np.array([2, 1, 1])

print(a[id_linhas, id_colunas])

print(a[:, [0,2]])

[  4  16 256]
[[  0   4]
 [  9  25]
 [ 36  64]
 [ 81 121]
 [144 196]
 [225 289]
 [324 400]]


### Indexando com booleanos

In [8]:
b = a > 200

print(b)

a[b]

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]


array([225, 256, 289, 324, 361, 400], dtype=int32)

In [9]:
# pode ser util para atribuição de valores
a[b] = 0
a

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196],
       [  0,   0,   0],
       [  0,   0,   0]], dtype=int32)