# Concatenação



In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.arange(7, 10)

print("a : ", a)
print("b : ", b)
print("c :", c)

a :  [1 2 3]
b :  [4 5 6]
c : [7 8 9]


In [2]:
print(np.concatenate((a,b)))
print(np.concatenate((b,a)))

[1 2 3 4 5 6]
[4 5 6 1 2 3]


In [3]:
print(np.concatenate((a, b, c)))

[1 2 3 4 5 6 7 8 9]


## Concatenando matrizes 

In [4]:
a = np.floor(10*np.random.random((2,2)))

print(a)

b = np.floor(10*np.random.random((2,2)))

print(b)

[[8. 6.]
 [9. 7.]]
[[1. 5.]
 [4. 1.]]


In [5]:
# equivale ao np.vstack((a, b))
print(np.concatenate((a,b), axis=0))

# equivale ao np.hstack((a, b))
print(np.concatenate((a,b), axis=1))

[[8. 6.]
 [9. 7.]
 [1. 5.]
 [4. 1.]]
[[8. 6. 1. 5.]
 [9. 7. 4. 1.]]


In [6]:
print(np.vstack((a, b)))

print(np.hstack((a, b)))

[[8. 6.]
 [9. 7.]
 [1. 5.]
 [4. 1.]]
[[8. 6. 1. 5.]
 [9. 7. 4. 1.]]


# Cópias

Nunca é criado uma cópia do array implicitamente.

In [7]:
a = np.arange(12)

b = a

# a e b são o mesma instanância
print(b is a, id(b), id(a)) 

b.shape = 3,4 # muda a
a.shape

True 2689253287616 2689253287616


(3, 4)

Python passa objetos mutaveis como referência, portanto a chamada de uma função não faz cópia.

In [8]:
def f(x):
    print(id(x))
    
print(id(a))
f(a)

2689253287616
2689253287616


Sclicing retorna uma view do array. Views são novos objetos do tipo ndarray que apontam para o mesmo dado.

In [9]:
s = a[:, 1:3]    
s[:] = 10      
a

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])

Portanto, é necessário fazer cópias explicitamente (quando desejado) através do método ```copy```.

In [10]:
# um novo objeto com um novo data é criado
d = a.copy()       

print(d is a)
# não compartilha nada com a
print(d.base is a)

d[0,0] = 9999
a

False
False


array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])